### PR TITLE
Changing browser policy and updating README.md

### PR DESCRIPTION
**Pull request by senthilp**

### CODE REVIEW

**Comment by senthilp** [comment]
Yes, until that is finalized we will have the eBayUI list. As you suggested we should update eBayUI to lookup this module for `browsersList`, so when we change here it automatically gets reflected. I have already created an issue for it — eBay/ebayui-core#97

**Comment by seangates** [comment]
So, to be clear, you don't mind keep it at `IE >= 11`? Or ... you want us to go back to supporting IE9? (The latter I don't agree with.)

**Comment by senthilp** [comment]
Until the official decision is made on IE9 we need to keep it. For eBayUI we supported IE9, right? Because it was part of the `browsersList` attribute.

**Comment by seangates** [comment]
No, we only supported IE11 forward ...

**Comment by seangates** [comment]
And to clarify, the browserslist config was made to match current support, but we knew that things might break for IE9/10, knowing we would more-than-likely drop them by the time we got to v1 for eBayUI.

**Comment by senthilp** [comment]
The issue is unless the official drop of IE9/10 happens, we cannot suggest this module for all other teams using Node.js. We want this module to be adopted across other projects, which will not happen if we drop IE9/10.

**Comment by seangates** [comment]
We need to convene the browser team ASAP ...

**Comment by senthilp** [comment]
Since eBayUI is on the only team using this module we can leave it as such. Once the decision is made, then will update the PR.

**Comment by seangates** [comment]
>Since eBayUI is on the only team using this module we can leave it as such.

Can you clarify? Keep it as it is _currently set in the repo_, or as this PR has it set?

e.g. `IE >= 9` or `IE >= 11`?

**Comment by senthilp** [comment]
Keep it as it is currently set in the repo

**Comment by seangates** [comment]
👍

**Pull request closed without merging**
